<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ItemsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table("items")->insert([
            [
                "item_name" => "腕時計",
                "price" => 15000,
                "description" => "スタイリッシュなデザインのメンズ腕時計",
                "image_path" => "https://coachtech-matter.s3.ap-northeast-1.amazonaws.com/image/Armani+Mens+Clock.jpg",
                "condition" => "良好",
                "user_id" => 1,
                "category_id" => 1,
                "brand_id" => 1,
                "status_id" => 1,
                "color_id" => 1,
                "sold_at" => null,
                "buyer_id" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "item_name" => "HDD",
                "price" => 5000,
                "description" => "高速で信頼性の高いハードディスク",
                "image_path" => "https://coachtech-matter.s3.ap-northeast-1.amazonaws.com/image/HDD+Hard+Disk.jpg",
                "condition" => "目立った傷や汚れなし",
                "user_id" => 2,
                "category_id" => 2,
                "brand_id" => 2,
                "status_id" => 2,
                "color_id" => 2,
                "sold_at" => null,
                "buyer_id" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "item_name" => "玉ねぎ3束",
                "price" => 300,
                "description" => "新鮮な玉ねぎ3束のセット",
                "image_path" => "https://coachtech-matter.s3.ap-northeast-1.amazonaws.com/image/iLoveIMG+d.jpg",
                "condition" => "やや傷や汚れあり",
                "user_id" => 3,
                "category_id" => 3,
                "brand_id" => 3,
                "status_id" => 3,
                "color_id" => 3,
                "sold_at" => null,
                "buyer_id" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "item_name" => "革靴",
                "price" => 4000,
                "description" => "クラシックなデザインの革靴",
                "image_path" => "https://coachtech-matter.s3.ap-northeast-1.amazonaws.com/image/Leather+Shoes+Product+Photo.jpg",
                "condition" => "状態が悪い",
                "user_id" => 4,
                "category_id" => 4,
                "brand_id" => 4,
                "status_id" => 4,
                "color_id" => 4,
                "sold_at" => null,
                "buyer_id" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "item_name" => "ノートPC",
                "price" => 45000,
                "description" => "高性能なノートパソコン",
                "image_path" => "https://coachtech-matter.s3.ap-northeast-1.amazonaws.com/image/Living+Room+Laptop.jpg",
                "condition" => "良好",
                "user_id" => 5,
                "category_id" => 5,
                "brand_id" => 5,
                "status_id" => 5,
                "color_id" => 5,
                "sold_at" => null,
                "buyer_id" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "item_name" => "マイク",
                "price" => 8000,
                "description" => "高音質のレコーディング用マイク",
                "image_path" => "https://coachtech-matter.s3.ap-northeast-1.amazonaws.com/image/Music+Mic+4632231.jpg",
                "condition" => "目立った傷や汚れなし",
                "user_id" => 6,
                "category_id" => 6,
                "brand_id" => 6,
                "status_id" => 6,
                "color_id" => 6,
                "sold_at" => null,
                "buyer_id" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "item_name" => "ショルダーバッグ",
                "price" => 3500,
                "description" => "おしゃれなショルダーバッグ",
                "image_path" => "https://coachtech-matter.s3.ap-northeast-1.amazonaws.com/image/Purse+fashion+pocket.jpg",
                "condition" => "やや傷や汚れあり",
                "user_id" => 7,
                "category_id" => 7,
                "brand_id" => 7,
                "status_id" => 7,
                "color_id" => 7,
                "sold_at" => null,
                "buyer_id" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "item_name" => "タンブラー",
                "price" => 500,
                "description" => "使いやすいタンブラー",
                "image_path" => "https://coachtech-matter.s3.ap-northeast-1.amazonaws.com/image/Tumbler+souvenir.jpg",
                "condition" => "状態が悪い",
                "user_id" => 8,
                "category_id" => 8,
                "brand_id" => 8,
                "status_id" => 8,
                "color_id" => 8,
                "sold_at" => null,
                "buyer_id" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "item_name" => "コーヒーミル",
                "price" => 4000,
                "description" => "手動のコーヒーミル",
                "image_path" => "https://coachtech-matter.s3.ap-northeast-1.amazonaws.com/image/Waitress+with+Coffee+Grinder.jpg",
                "condition" => "良好",
                "user_id" => 9,
                "category_id" => 9,
                "brand_id" => 9,
                "status_id" => 9,
                "color_id" => 9,
                "sold_at" => null,
                "buyer_id" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            [
                "item_name" => "メイクセット",
                "price" => 2500,
                "description" => "便利なメイクアップセット",
                "image_path" => "https://coachtech-matter.s3.ap-northeast-1.amazonaws.com/image/%E5%A4%96%E5%87%BA%E3%83%A1%E3%82%A4%E3%82%AF%E3%82%A2%E3%83%83%E3%83%95%E3%82%9A%E3%82%BB%E3%83%83%E3%83%88.jpg",
                "condition" => "目立った傷や汚れなし",
                "user_id" => 10,
                "category_id" => 10,
                "brand_id" => 10,
                "status_id" => 10,
                "color_id" => 10,
                "sold_at" => null,
                "buyer_id" => null,
                "created_at" => now(),
                "updated_at" => now(),
            ],
            // Add more items as needed
        ]);
    }
}
